#declare USE_B_PAWN_0 = 1;
#declare USE_B_PAWN_1 = 1;
#declare USE_B_PAWN_2 = 1;
#declare USE_B_PAWN_3 = 1;
#declare USE_B_PAWN_4 = 1;
#declare USE_B_PAWN_5 = 1;
#declare USE_B_PAWN_6 = 1;
#declare USE_B_PAWN_7 = 1;

#declare USE_B_ROOK_1 = 1;
#declare USE_B_KNIGHT_1 = 1;
#declare USE_B_BISHOP_1 = 1;
#declare USE_B_QUEEN = 1;
#declare USE_B_KING = 1;
#declare USE_B_ROOK_2 = 1;
#declare USE_B_KNIGHT_2 = 1;
#declare USE_B_BISHOP_2 = 1;

#declare USE_W_PAWN_0 = 1;
#declare USE_W_PAWN_1 = 1;
#declare USE_W_PAWN_2 = 1;
#declare USE_W_PAWN_3 = 1;
#declare USE_W_PAWN_4 = 1;
#declare USE_W_PAWN_5 = 1;
#declare USE_W_PAWN_6 = 1;
#declare USE_W_PAWN_7 = 1;

#declare USE_W_ROOK_1 = 1;
#declare USE_W_KNIGHT_1 = 1;
#declare USE_W_BISHOP_1 = 1;
#declare USE_W_QUEEN = 1;
#declare USE_W_KING = 1;
#declare USE_W_ROOK_2 = 1;
#declare USE_W_KNIGHT_2 = 1;
#declare USE_W_BISHOP_2 = 1;